"""empty message

Revision ID: 155007c9f9b0
Revises: 
Create Date: 2020-05-16 22:42:30.150825

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '155007c9f9b0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'follows',
        existing_comment='This table stores the follow information for the application',
        schema=None
    )
    op.drop_table_comment(
        'likes',
        existing_comment='This table stores the likes data of the application',
        schema=None
    )
    op.create_index(op.f('ix_posts_created_on'), 'posts', ['created_on'], unique=False)
    op.drop_index('fki_main', table_name='posts')
    op.drop_constraint('main', 'posts', type_='foreignkey')
    op.drop_table_comment(
        'posts',
        existing_comment='This database stores post for the application',
        schema=None
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_joined_on'), 'users', ['joined_on'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_constraint('User_unique', 'users', type_='unique')
    op.drop_table_comment(
        'users',
        existing_comment='This table is used to store details relating to the User for the application',
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'users',
        'This table is used to store details relating to the User for the application',
        existing_comment=None,
        schema=None
    )
    op.create_unique_constraint('User_unique', 'users', ['username'])
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_joined_on'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_table_comment(
        'posts',
        'This database stores post for the application',
        existing_comment=None,
        schema=None
    )
    op.create_foreign_key('main', 'posts', 'users', ['user_id'], ['id'])
    op.create_index('fki_main', 'posts', ['user_id'], unique=False)
    op.drop_index(op.f('ix_posts_created_on'), table_name='posts')
    op.create_table_comment(
        'likes',
        'This table stores the likes data of the application',
        existing_comment=None,
        schema=None
    )
    op.create_table_comment(
        'follows',
        'This table stores the follow information for the application',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###
